name: Python package (tests + lint + build)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests on Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # نصب پکیج به صورت editable + ابزارهای توسعه
          pip install -e .
          pip install pytest pytest-cov ruff build

      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests (with coverage)
        run: |
          pytest -q --cov=iran_national_id --cov-report=term-missing --cov-report=xml

      - name: Build package (sdist & wheel)
        run: python -m build
